[project]
name = "receiptparser"
description = "Parses receipt from spanish supermarkets"
requires-python = "~=3.12"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = ["receipt_parser"]

[tool.mypy]
ignore_missing_imports = true

[tool.black]
include = '\.pyi?$'
